### PR TITLE
Laravel 10.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l10-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/hedii/laravel-gelf-logger/pull/39/commits/d97ec577932b9880a6051eff7951b82effd7b354?w=1) for Laravel 10. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-gelf-logger.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "hedii/laravel-gelf-logger": "dev-l10-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by arnidan** [comment]
@hedii 

Hello! Could you review that pull request?

Thank you!

**Comment by hedii** [comment]
@arnidan I am missing time for the moment.

This automated pull request is quite dumb, it bumps graylog2/gelf-php from 1.x to 2.x without any modification in code appart from composer.json.

Such an annoying thing (@laravel-shift if you hear me, you should stop doing these automated PR, it is nothing but hidden advertising for your paid for products, zero value...).

I have plan to update everything, from laravel version to gelf-php version, but it needs some work.

@arnidan If you have time, I would be happy to review your own pull request.

Thanks

**Comment by jasonmccreary** [comment]
It's meant to help. But if you don't find value like the hundreds of other package authors who have merged their PRs, then I will gladly remove you from our automated list.

**Comment by hedii** [comment]
@jasonmccreary please remove, thanks.

I know my maths, 10 is after 9. Appart from that, i don't see anything helpful in this PR ;)

Appart some sort of notification that there is a new laravel version available, i have twitter for that.

**Comment by jasonmccreary** [comment]
All good. Just trying to help the community. But you're clearly a nonda, so you don't see that.

**Pull request closed without merging**
